### ISSUE TITLE
Where is the fusion part?

### ISSUE THREAD

**Issue by zhangjun-xyz** [JunshengFu/tracking-with-Extended-Kalman-Filter#2]
Hello I read all your codes but I cannot the fusion part. In your codes lidar and radar data are processed, respectively. I don't know whether my understand is right.

**Comment by JunshengFu** [comment]
@zhangjun-xyz 
The fusion part is here: [void FusionEKF::ProcessMeasurement(const MeasurementPackage &measurement_pack) {}](https://github.com/JunshengFu/tracking-with-Extended-Kalman-Filter/blob/535ef39a9ac2ba0d366426bf227c867e5fea9ca3/src/FusionEKF.cpp#L68)

Lidar and radar data should be processed respectively since they are different measurements: lidar: px and py (pz is not used in this project); radar: range, bearing, radial velocity. 

You can see how EKF works [here](https://github.com/JunshengFu/tracking-with-Extended-Kalman-Filter/blob/master/data/ekf_flow.jpg), and you may find these following two material useful for understanding EKF. 
http://home.wlu.edu/~levys/kalman_tutorial/
http://biorobotics.ri.cmu.edu/papers/sbp_papers/integrated3/kleeman_kalman_basics.pdf

**Comment by zhangjun-xyz** [comment]
Thanks a lot!
I found that. So the fusion is to process the measurements given by the two sensors successively. Is my understanding right?

**Comment by JunshengFu** [comment]
@zhangjun-xyz  check this out: https://en.wikipedia.org/wiki/Sensor_fusion
"Sensor fusion is combining of sensory data or data derived from disparate sources such that the resulting information has less uncertainty than would be possible when these sources were used individually... "

**Comment by zhangjun-xyz** [comment]
Okay, I understand. Thanks for your sharing.
